CONFIG_PATH = 'config/config.json'
SELECTOR_PATH = 'config/gift_selector.json'
VARIANT_SELECTOR = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > div.Transition.pP8TxefR > div.Transition_slide.Transition_slide-active > div > div > div.Transition_slide.Transition_slide-active > div > div:nth-child(1)'
BUY_BUTTON_SELECTOR = '#portals > div:nth-child(3) > div > div.modal-container > div.modal-dialog > div.modal-content.custom-scroll.KYHkJ9Qf > div.bho0GTYt > button'  # замените на реальный селектор кнопки покупки
MENU_SELECTOR = 'button[aria-label*="Open menu"], button[title*="Open menu"]'
SETTINGS_SELECTOR = '//div[contains(@class, "MenuItem") and .//i[contains(@class, "icon-settings")]]'
SEND_GIFT = '//div[contains(@class, "ListItem-button") and .//i[contains(@class, "icon-gift")]]'
TARGET_CONTACT = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div.modal-content.custom-scroll.FuFYE0AA > div > div.yLCbiItq.bXzIGw8s.custom-scroll > div:nth-child(1)'
TARGET_TYPE_GIFT = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > div.Transition.pP8TxefR > div > div > div.Transition.kB6IyXqS > div > div > div:nth-child(14)'
TARGET_GIFT = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > div.Transition.pP8TxefR > div.Transition_slide.Transition_slide-active > div > div > div.Transition_slide.Transition_slide-active > div > div:nth-child(1)'
TARGET_PRICE = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > div.Transition.pP8TxefR > div.Transition_slide.Transition_slide-active > div > div > div.Transition_slide.Transition_slide-active > div > div:nth-child(1) > button > i'
SECOND_PRICE = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > div.Transition.pP8TxefR > div.Transition_slide.Transition_slide-active > div > div > div.Transition_slide.Transition_slide-active > div > div:nth-child(2) > button > i'
THIRD_PRICE = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > div.Transition.pP8TxefR > div.Transition_slide.Transition_slide-active > div > div > div.Transition_slide.Transition_slide-active > div > div:nth-child(3) > button > i'
RETURN_TO_TYPE_GIFT_BUTTON = '#portals > div:nth-child(2) > div > div > div.modal-dialog > div > button'
PAY_BUTTON_FOR_TARGET_GIFT = '#portals > div:nth-child(3) > div > div.modal-container > div.modal-dialog > div.modal-content.custom-scroll.KYHkJ9Qf > div.bho0GTYt > button'
EXIT_FROM_PAYING_GIFT_BUTTON = '#portals > div:nth-child(3) > div > div.modal-container > div.modal-dialog > div.ie9tImaj > div > div.WA0INleU.rJOB1u5Q'
